version: '3.0'

volumes:
  service-vol:
  postgres-vol:

services:
  node-service:
    image: node-servise
    build: .
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - service-vol:/app/logs
      - ./:/app
    depends_on:
      - postgres
    networks:
      - network
  postgres:
    image: node-base
    build: postgres
    container_name: postgres
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    networks:
      - network
networks:
  network:
    name: my-bridge
    driver: bridge
